version: '3'
services:

  angular:
    container_name: collabus_prod_angular
    hostname: angular
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.prod
      args:
        - execution_environment=${EXECUTION_ENVIRONMENT:-production}
    ports:
      - ${COLLABUS_FRONTEND_PORT:-80}:80
    volumes:
      - ../data.keep/log/nginx_frontend:/var/log/nginx
