version: '3'
services:
  angular:
    container_name: collabus_prod_angular
    image: collabus_frontend
    hostname: angular
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
