version: '3'
services:

  angular:
    container_name: collabus_prod_angular
    image: collabus_frontend
    hostname: angular
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.prod
      args:
        - execution_environment=${EXECUTION_ENVIRONMENT:-production}
    ports:
      - ${COLLABUS_FRONTEND_PORT:-80}:80
