version: '3'
services:

  django:
    container_name: collabus_prod_django
    image: collabus_backend
    hostname: django
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      - ./out/static:/app/static:rw
      - ./out/media:/app/media:rw
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: collabus_prod_postgres
    image: postgres:15
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DJANGO_DATABASE_PSWD}
      POSTGRES_USER: ${DJANGO_DATABASE_USER}
      POSTGRES_DB: ${DJANGO_DATABASE_NAME}
      PGPORT: 5432
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./out/pgdata:/var/lib/postgresql/data/pgdata:rw

  redis:
    container_name: collabus_prod_redis
    image: redis:7
    hostname: redis
    restart: always

  nginx:
    container_name: collabus_prod_nginx
    image: nginx:1.23-alpine
    restart: always
    ports:
      - ${COLLABUS_BACKEND_PORT:-80}:80
    volumes:
      - ./out/static:/app/static:ro
      - ./out/media:/app/media:ro
      - ./docker:/etc/nginx/conf.d:ro
