# Generated by Django 4.1.3 on 2023-02-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
