# Generated by Django 4.1.3 on 2023-03-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0003_alter_folder_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Identité visuelle'), (2, 'Charte graphique'), (3, 'Création de logo'), (4, 'Parcours utilisateur'), (5, 'Maquettage graphique'), (6, 'Développement de site'), (7, "Développement d'application"), (8, 'Développement de logiciel'), (9, 'Spécifications technique et fonctionnelle'), (10, 'Gestion et organisation de projet'), (11, 'Stratégie de communication'), (12, 'Stratégie digitale'), (13, 'Analyse de marché'), (14, 'Campagne publicitaire'), (15, 'Stratégie de prix et de distribution')]),
        ),
    ]
