# Generated by Django 4.1.3 on 2023-02-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='siret',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
