# Generated by Django 4.1.3 on 2023-03-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_entity_siret'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='activity',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
